root = "."
tmp_dir = "tmp"

[build]
  cmd = "clear && cd frontend && npm run build && cd .. && go build -o tmp/main ."
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go","tsx","ts","css","html"]
  exclude_dir = ["frontend/dist", "frontend/node_modules"]

[log]
  time = true

[misc]
  clean_on_exit = true